### ISSUE TITLE
Issue Warning to SSL Errors due to Dated Cipher Suites

### ISSUE THREAD

**Issue by jake-bickle** [jake-bickle/Arachnid#15]
Attempting to execute the following
```
import requests
requests.get("https://mail.calcharter.org")
```

Results in the following error
```
Traceback (most recent call last):
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1640, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mail.calcharter.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/__main__.py", line 3, in <module>
    main()
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/arachnid.py", line 191, in main
    crawl()
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/arachnid.py", line 175, in crawl
    while c.crawl_next():
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/crawler/crawler.py", line 66, in crawl_next
    c_url = self.schedule.next_url()
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/crawler/scheduler.py", line 85, in next_url
    self._fuzz_for_domainblocks()
  File "/Users/jacobbickle/PycharmProjects/Arachnid/arachnid/crawler/scheduler.py", line 113, in _fuzz_for_domainblocks
    r = requests.head(sub_to_check.get_url(), headers=self.headers)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jacobbickle/.local/share/virtualenvs/Arachnid-do6dGE4u/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mail.calcharter.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
```

After some research, I've found a similar situation [here](https://github.com/psf/requests/issues/4638). After trying out some possible solutions, I've found that its due to cipher suites that the requests library no longer supports.

It's possible to add these cipher suites manually, but there are likely too many edge cases around the internet to keep track of. I decided that it'd be best to only use the Cipher Suites that requests supports. Because of this decision, Arachnid can't access the website and must notify the user by a warning.

**Comment by jake-bickle** [comment]
Completed on commit 69d3deb6e92a2431ff965ec6b68db0ddb9624a04
